apiVersion: v1
kind: Pod
metadata:
  name: joomla
  labels:
    name: joomla
spec:
  containers:
  - name: joomla
    image:  joomla:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
          name: joomla