apiVersion: v1
kind: Service
metadata:
  name: joomla
  labels:
    app: joomla
spec:
  type:  NodePort
  ports:
  - name: joomlaports
    port: 80
    targetPort: 80
    nodePort: 30015
  selector:
    app: joomla
  
  