apiVersion: v1
kind: Service
metadata:
  name:  mariadb
  labels:
    app: mariadb
spec:
  type:  NodePort
  ports:
  - name:  mariadbports
    port:  3306
    targetPort:  3306
    nodePort: 30010
  selector:
    app:  mariadb
    