apiVersion: v1
kind: Service
metadata:
  name:  svc-joomla
  labels:
    app: svc-joomla
spec:
  ports:
  - name:  keyports
    port:  1500
    targetPort:  1500
  selector:
    app:  joomla
  type:  NodePort